# Resume hackathon deploy from step 4 (schema already applied)
$ErrorActionPreference = "Continue"
$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $repoRoot

function Get-SecretValue([string]$name) {
    $line = Get-Content "hackathon.secrets.env" | Where-Object { $_ -match "^\s*$name\s*=" } | Select-Object -First 1
    if (-not $line) { return "" }
    $value = ($line -split "=", 2)[1].Trim().Trim('"').Trim("'")
    return $value -replace "`r", ""
}

$projectRef = Get-SecretValue "SUPABASE_PROJECT_REF"
if ([string]::IsNullOrWhiteSpace($projectRef)) { $projectRef = "oxvfbrxoooindyrqvjgk" }
$anonKey = Get-SecretValue "SUPABASE_ANON_KEY"
$serviceRoleKey = Get-SecretValue "SUPABASE_SERVICE_ROLE_KEY"
$lovableKey = Get-SecretValue "LOVABLE_API_KEY"
$dbPassword = Get-SecretValue "SUPABASE_DB_PASSWORD"
$env:SUPABASE_DB_PASSWORD = $dbPassword

$supabaseUrl = "https://$projectRef.supabase.co"

Write-Host "[A] Creating test user..." -ForegroundColor Yellow
if ($serviceRoleKey) {
    $authUrl = "$supabaseUrl/auth/v1/admin/users"
    $listUrl = "$authUrl" + "?page=1&per_page=50"
    try {
        $existing = Invoke-RestMethod -Uri $listUrl -Headers @{
            apikey = $serviceRoleKey
            Authorization = "Bearer $serviceRoleKey"
        } -Method Get

        $found = $existing.users | Where-Object { $_.email -eq "test@example.com" }
        if ($found) {
            Write-Host "  User already exists." -ForegroundColor Gray
        } else {
            $body = @{
                email = "test@example.com"
                password = "TestPassword123!"
                email_confirm = $true
                user_metadata = @{ full_name = "Hackathon Test User" }
            } | ConvertTo-Json
            Invoke-RestMethod -Uri $authUrl -Method Post -Headers @{
                apikey = $serviceRoleKey
                Authorization = "Bearer $serviceRoleKey"
                "Content-Type" = "application/json"
            } -Body $body | Out-Null
            Write-Host "  User created." -ForegroundColor Green
        }
    } catch {
        Write-Host "  Auth failed: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

Write-Host "[B] Bootstrap SQL..." -ForegroundColor Yellow
npx supabase db query --linked -f scripts/post-migration-hackathon-bootstrap.sql

Write-Host "[C] Writing .env.local..." -ForegroundColor Yellow
$envLocal = @(
    "# Generated by scripts/hackathon-deploy-resume.ps1"
    "VITE_SUPABASE_URL=`"$supabaseUrl`""
    "VITE_SUPABASE_PUBLISHABLE_KEY=`"$anonKey`""
    "VITE_SUPABASE_ANON_KEY=`"$anonKey`""
    "VITE_SUPABASE_PROJECT_ID=`"$projectRef`""
    "VITE_API_BASE_URL=`"$supabaseUrl/functions/v1`""
    "VITE_DEMO_LOGIN_EMAIL=test@example.com"
    "VITE_DEMO_LOGIN_PASSWORD=TestPassword123!"
) -join "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Join-Path $repoRoot ".env.local"), $envLocal, $utf8NoBom)
Write-Host "  Done." -ForegroundColor Green

Write-Host "[D] Deploying Edge Function..." -ForegroundColor Yellow
if ($lovableKey) {
    npx supabase secrets set "LOVABLE_API_KEY=$lovableKey" --project-ref $projectRef
}
npx supabase functions deploy triage-project-task --project-ref $projectRef

Write-Host ""
Write-Host "Resume complete. Restart: npm run dev" -ForegroundColor Green
