# =============================================================================
# Hackathon one-command deploy (minimal DB — skips full db push)
# =============================================================================
# Usage:
#   1. Copy hackathon.secrets.env.example → hackathon.secrets.env
#   2. Fill in all values from Supabase Dashboard
#   3. Run: .\scripts\hackathon-deploy-all.ps1
#
# Requires: Supabase CLI logged in as owner of the hackathon project
#   npx supabase login
# =============================================================================

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $repoRoot

$secretsPath = Join-Path $repoRoot "hackathon.secrets.env"
if (-not (Test-Path $secretsPath)) {
    Write-Host "Missing hackathon.secrets.env" -ForegroundColor Red
    Write-Host "Copy hackathon.secrets.env.example → hackathon.secrets.env and fill in values." -ForegroundColor Yellow
    exit 1
}

function Get-SecretValue([string]$name) {
    $line = Get-Content $secretsPath | Where-Object { $_ -match "^\s*$name\s*=" } | Select-Object -First 1
    if (-not $line) { return "" }
    $value = ($line -split "=", 2)[1].Trim().Trim('"').Trim("'")
    return $value -replace "`r", ""
}

$projectRef = Get-SecretValue "SUPABASE_PROJECT_REF"
$anonKey = Get-SecretValue "SUPABASE_ANON_KEY"
$serviceRoleKey = Get-SecretValue "SUPABASE_SERVICE_ROLE_KEY"
$dbPassword = Get-SecretValue "SUPABASE_DB_PASSWORD"
$lovableKey = Get-SecretValue "LOVABLE_API_KEY"
$vercelToken = Get-SecretValue "VERCEL_TOKEN"

if ([string]::IsNullOrWhiteSpace($projectRef)) { $projectRef = "oxvfbrxoooindyrqvjgk" }
if ([string]::IsNullOrWhiteSpace($anonKey) -or [string]::IsNullOrWhiteSpace($dbPassword)) {
    Write-Host "SUPABASE_ANON_KEY and SUPABASE_DB_PASSWORD are required in hackathon.secrets.env" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Hackathon deploy → project $projectRef" -ForegroundColor Cyan
Write-Host ""

# Link + DB password for Management API
$env:SUPABASE_DB_PASSWORD = $dbPassword

Write-Host "[1/7] Linking Supabase project..." -ForegroundColor Yellow
npx supabase link --project-ref $projectRef --password $dbPassword
if ($LASTEXITCODE -ne 0) {
    Write-Host "Link failed. Run: npx supabase login (must be owner of $projectRef)" -ForegroundColor Red
    exit 1
}

Write-Host "[2/7] Applying minimal hackathon schema (SQL)..." -ForegroundColor Yellow
npx supabase db query --linked -f scripts/hackathon-minimal-schema.sql
if ($LASTEXITCODE -ne 0) {
    Write-Host "Schema SQL failed. Check DB password and CLI login." -ForegroundColor Red
    exit 1
}

Write-Host "[3/7] Creating test user test@example.com ..." -ForegroundColor Yellow
if (-not [string]::IsNullOrWhiteSpace($serviceRoleKey)) {
    $authUrl = "https://$projectRef.supabase.co/auth/v1/admin/users"
    $body = @{
        email = "test@example.com"
        password = "TestPassword123!"
        email_confirm = $true
        user_metadata = @{ full_name = "Hackathon Test User" }
    } | ConvertTo-Json

    try {
        $existing = Invoke-RestMethod -Uri "$authUrl?page=1&per_page=50" -Headers @{
            apikey = $serviceRoleKey
            Authorization = "Bearer $serviceRoleKey"
        } -Method Get

        $found = $existing.users | Where-Object { $_.email -eq "test@example.com" }
        if ($found) {
            Write-Host "  User already exists, skipping create." -ForegroundColor Gray
        } else {
            Invoke-RestMethod -Uri $authUrl -Method Post -Headers @{
                apikey = $serviceRoleKey
                Authorization = "Bearer $serviceRoleKey"
                "Content-Type" = "application/json"
            } -Body $body | Out-Null
            Write-Host "  User created." -ForegroundColor Green
        }
    } catch {
        Write-Host "  Auth API failed: $($_.Exception.Message)" -ForegroundColor Yellow
        Write-Host "  Create user manually in Dashboard -> Auth -> Users" -ForegroundColor Yellow
    }
} else {
    Write-Host "  No SERVICE_ROLE_KEY — create test@example.com manually in Auth UI" -ForegroundColor Yellow
}

Write-Host "[4/7] Running bootstrap SQL (admin role + verify tasks)..." -ForegroundColor Yellow
npx supabase db query --linked -f scripts/post-migration-hackathon-bootstrap.sql
if ($LASTEXITCODE -ne 0) { exit 1 }

Write-Host "[5/7] Writing .env.local ..." -ForegroundColor Yellow
$supabaseUrl = "https://$projectRef.supabase.co"
$envLocal = @(
    "# Generated by scripts/hackathon-deploy-all.ps1"
    "VITE_SUPABASE_URL=`"$supabaseUrl`""
    "VITE_SUPABASE_PUBLISHABLE_KEY=`"$anonKey`""
    "VITE_SUPABASE_ANON_KEY=`"$anonKey`""
    "VITE_SUPABASE_PROJECT_ID=`"$projectRef`""
    "VITE_API_BASE_URL=`"$supabaseUrl/functions/v1`""
    "VITE_DEMO_LOGIN_EMAIL=test@example.com"
    "VITE_DEMO_LOGIN_PASSWORD=TestPassword123!"
) -join "`n"
Set-Content -Path (Join-Path $repoRoot ".env.local") -Value $envLocal -Encoding utf8NoBOM
Write-Host "  .env.local created" -ForegroundColor Green

Write-Host "[6/7] Deploying triage-project-task Edge Function..." -ForegroundColor Yellow
if (-not [string]::IsNullOrWhiteSpace($lovableKey)) {
    npx supabase secrets set "LOVABLE_API_KEY=$lovableKey" --project-ref $projectRef
}
npx supabase functions deploy triage-project-task --project-ref $projectRef
if ($LASTEXITCODE -ne 0) {
    Write-Host "Function deploy failed. Set LOVABLE_API_KEY in Dashboard → Edge Functions → Secrets" -ForegroundColor Yellow
}

Write-Host "[7/7] Vercel deploy (optional)..." -ForegroundColor Yellow
if (-not [string]::IsNullOrWhiteSpace($vercelToken)) {
    $env:VERCEL_TOKEN = $vercelToken
    npx vercel deploy --prod --yes `
        -e "VITE_SUPABASE_URL=$supabaseUrl" `
        -e "VITE_SUPABASE_PUBLISHABLE_KEY=$anonKey" `
        -e "VITE_SUPABASE_ANON_KEY=$anonKey" `
        -e "VITE_SUPABASE_PROJECT_ID=$projectRef" `
        -e "VITE_API_BASE_URL=$supabaseUrl/functions/v1" `
        -e "VITE_DEMO_LOGIN_EMAIL=test@example.com" `
        -e "VITE_DEMO_LOGIN_PASSWORD=TestPassword123!"
} else {
    Write-Host "  No VERCEL_TOKEN — deploy manually at vercel.com with same env vars as .env.local" -ForegroundColor Gray
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host " Hackathon deploy complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Local:  npm run dev  →  http://localhost:8080" -ForegroundColor White
Write-Host "Login:  test@example.com / TestPassword123!" -ForegroundColor White
Write-Host "Demo:   BD → All Tasks → Site down???" -ForegroundColor White
Write-Host "Direct: http://localhost:8080/bd/actions/tasks/a0000011-0000-4000-8000-000000000011" -ForegroundColor Gray
Write-Host ""
