# Setup personal Supabase cloud project for SJ BD Dashboard (hackathon)
# Applies ALL migrations from this repo - does NOT connect to the team database.
#
# Usage (PowerShell):
#   cd C:\Users\pc\sj-bd-dashboard
#   .\scripts\setup-personal-supabase.ps1

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host " Personal Supabase Setup (Hackathon)" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script will:" -ForegroundColor White
Write-Host "  1. Log you into Supabase CLI (browser)" -ForegroundColor Gray
Write-Host "  2. Link YOUR cloud project to this repo" -ForegroundColor Gray
Write-Host "  3. Push all database migrations (schema + seeds in repo)" -ForegroundColor Gray
Write-Host "  4. Create .env.local pointing at YOUR project" -ForegroundColor Gray
Write-Host ""
Write-Host "You need BEFORE running:" -ForegroundColor Yellow
Write-Host "  - A Supabase project created at https://supabase.com/dashboard" -ForegroundColor Gray
Write-Host "  - Project ref from URL: https://supabase.com/dashboard/project/<PROJECT_REF>" -ForegroundColor Gray
Write-Host "  - Database password you set when creating the project" -ForegroundColor Gray
Write-Host ""

$projectRef = Read-Host "Enter your Supabase PROJECT REF (e.g. oxvfbrxoooindyrqvjgk)"
if ([string]::IsNullOrWhiteSpace($projectRef)) {
    Write-Host "Project ref is required." -ForegroundColor Red
    exit 1
}

$anonKey = Read-Host "Enter your anon PUBLIC key (Project Settings -> API -> anon public)"
if ([string]::IsNullOrWhiteSpace($anonKey)) {
    Write-Host "Anon key is required." -ForegroundColor Red
    exit 1
}

$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $repoRoot

Write-Host ""
Write-Host "Step 1: Supabase CLI login (browser will open)..." -ForegroundColor Yellow
npx supabase login
if ($LASTEXITCODE -ne 0) {
    Write-Host "Login failed. Try again or run: npx supabase login" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Step 2: Linking project $projectRef ..." -ForegroundColor Yellow
Write-Host "(You may be prompted for your database password)" -ForegroundColor Gray
npx supabase link --project-ref $projectRef
if ($LASTEXITCODE -ne 0) {
    Write-Host "Link failed. Check project ref and database password." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Step 3: Pushing migrations (may take 5-15 minutes)..." -ForegroundColor Yellow
npx supabase db push
if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "db push failed - see errors above." -ForegroundColor Red
    Write-Host "Share the error text with your mentor / Cursor chat (not your passwords)." -ForegroundColor Yellow
    Write-Host "Fallback: run hackathon SQL only in Dashboard SQL Editor:" -ForegroundColor Yellow
    Write-Host "  supabase/migrations/20260620120000_task_triage_agent.sql" -ForegroundColor Gray
    exit 1
}

$supabaseUrl = "https://$projectRef.supabase.co"
$functionsUrl = "$supabaseUrl/functions/v1"

$envLocalPath = Join-Path $repoRoot ".env.local"
$envLines = @(
    "# Personal Supabase - generated by scripts/setup-personal-supabase.ps1"
    "# Overrides .env (team project). Safe to keep local only."
    ""
    "VITE_SUPABASE_URL=`"$supabaseUrl`""
    "VITE_SUPABASE_PUBLISHABLE_KEY=`"$anonKey`""
    "VITE_SUPABASE_ANON_KEY=`"$anonKey`""
    "VITE_SUPABASE_PROJECT_ID=`"$projectRef`""
    "VITE_API_BASE_URL=`"$functionsUrl`""
    "EXA_API_KEY=`"your-exa-api-key`""
)
Set-Content -Path $envLocalPath -Value ($envLines -join "`n") -Encoding UTF8

Write-Host ""
Write-Host "=========================================" -ForegroundColor Green
Write-Host " Setup complete!" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Created: .env.local (your personal project - overrides .env)" -ForegroundColor Green
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "  1. Supabase Dashboard -> Authentication -> Users -> Add user" -ForegroundColor White
Write-Host "     Email: test@example.com  Password: TestPassword123!  Auto-confirm: Yes" -ForegroundColor Gray
Write-Host "  2. SQL Editor -> run scripts/post-migration-hackathon-bootstrap.sql" -ForegroundColor White
Write-Host "  3. npm run dev  ->  http://localhost:8080  -> log in" -ForegroundColor White
Write-Host "  4. BD -> All Tasks -> look for Site down??? demo task" -ForegroundColor White
Write-Host ""
Write-Host "Share with Cursor (safe):" -ForegroundColor Yellow
Write-Host "  - Project ref: $projectRef" -ForegroundColor Gray
Write-Host "  - Whether login / tasks page works" -ForegroundColor Gray
Write-Host "  - Any error messages (not keys or passwords)" -ForegroundColor Gray
Write-Host ""
