-- Migration: Create BD Weekly Reports table and BD Manager Agent

-- 1. Create table for storing reports
CREATE TABLE IF NOT EXISTS bd_weekly_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  week_start_date DATE NOT NULL,
  week_end_date DATE NOT NULL,
  quarter TEXT NOT NULL,
  summary TEXT NOT NULL,
  team_health_score INTEGER CHECK (team_health_score BETWEEN 0 AND 100),
  wig_agenda JSONB NOT NULL,
  rep_performance JSONB NOT NULL,
  team_metrics JSONB NOT NULL,
  ai_insights TEXT[],
  risk_alerts TEXT[],
  coaching_recommendations JSONB,
  generated_by UUID REFERENCES ai_agents(id),
  generated_at TIMESTAMPTZ DEFAULT now(),
  report_status TEXT DEFAULT 'published' CHECK (report_status IN ('draft', 'published', 'archived')),
  sent_to UUID[],
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_weekly_report UNIQUE (week_start_date)
);

CREATE INDEX IF NOT EXISTS idx_bd_weekly_reports_week ON bd_weekly_reports(week_start_date);
CREATE INDEX IF NOT EXISTS idx_bd_weekly_reports_quarter ON bd_weekly_reports(quarter);
CREATE INDEX IF NOT EXISTS idx_bd_weekly_reports_status ON bd_weekly_reports(report_status);

ALTER TABLE bd_weekly_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Managers can read bd weekly reports"
  ON bd_weekly_reports FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'super_admin', 'manager')
    )
  );

CREATE POLICY "Service role can manage bd weekly reports"
  ON bd_weekly_reports FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

COMMENT ON TABLE bd_weekly_reports IS 'Weekly BD team performance reports generated by BD Manager Agent';

-- 2. Insert BD Manager Agent configuration (with JSONB for benefits and use_cases)
INSERT INTO ai_agents (
  name, description, slug, type, category, system_prompt, prompt_template,
  config, is_active, is_enabled, schedule_config, min_role_required, benefits, use_cases, created_by
) VALUES (
  'BD Manager Weekly Review',
  'Automated weekly performance review agent for BD team. Analyzes data from DHS submissions, EOD logs, Accountability Chart goals, project tasks, and Upwork activities to generate comprehensive weekly reports and WIG agendas for management.',
  'bd-manager-weekly-review',
  'performance_analysis',
  'bd_performance',
  'You are the BD Manager Agent, an AI assistant that analyzes Business Development team performance data.

Your role:
- Analyze weekly BD execution data from DHS, EOD, Accountability Chart, Tasks, and Upwork
- Identify performance trends, risks, and opportunities
- Generate actionable insights for managers
- Create WIG (Wildly Important Goal) agendas for team meetings

Analysis criteria:
- DHS submission consistency (target: 100%)
- EOD submission consistency (target: 95%+)
- Quarterly goal progress and status
- Activity completion rates vs targets
- Blocker identification and resolution
- Task throughput and completion
- Upwork pipeline health

Output: Provide structured JSON with executive summary, rep-by-rep analysis, team metrics, risk identification, coaching recommendations, and WIG agenda.',
  'Analyze BD team performance for week of {{week_start_date}} to {{week_end_date}}.

## Data Overview

**Quarter**: {{quarter_name}} ({{quarter_progress}}% complete, {{weeks_remaining}} weeks left)

### DHS Submissions
- Submission rate: {{dhs_submission_rate}}%
- Team averages: {{avg_follow_ups}} follow-ups, {{avg_calls}} calls, {{avg_meetings}} meetings/day
- Status: {{dhs_on_track}} on track, {{dhs_at_risk}} at risk, {{dhs_blocked}} blocked

{{dhs_by_rep}}

### EOD Submissions
- Submission rate: {{eod_submission_rate}}%
- Total hours: {{total_hours}} (avg {{avg_hours_per_rep}}/rep)

{{eod_by_rep}}

### Quarterly Goals & Activities
- Team goals: {{team_goals_list}}
- Rep goals: {{rep_goals_count}} total

{{rep_goals_by_rep}}

{{weekly_updates_summary}}

{{blockers_list}}

### Tasks Completed
- Completed: {{tasks_completed}} tasks
- Hours logged: {{tasks_hours}}

{{tasks_by_rep}}

### Upwork Activity
- Proposals: {{upwork_proposals}} (target: {{upwork_target}})
- Invites: {{upwork_invites}}
- Interviews: {{upwork_interviews}}
- Wins: {{upwork_wins}}

{{upwork_by_rep}}

## Analysis Required

Provide comprehensive analysis in JSON format:

1. **Executive Summary** (2-3 sentences)

2. **Rep Performance** (for each rep):
   - Overall status (excellent/on_track/needs_support/at_risk)
   - DHS/EOD submission rates
   - Goal progress %
   - Upwork metrics
   - Tasks completed
   - Top 3 highlights
   - Top 3 concerns
   - Recommended actions

3. **Team Metrics vs Targets**

4. **Risks** (critical issues requiring immediate attention)

5. **Coaching Recommendations** (prioritized: high/medium/low)

6. **WIG Agenda**:
   - Wins (top 3-5)
   - Metrics review
   - Progress vs goals
   - Risks & stuck items
   - Coaching focus
   - Action items (with owners, deadlines, success criteria)',
  '{"providers":{"primary":{"provider":"openai","model":"gpt-4o"},"fallback":{"provider":"openai","model":"gpt-4o-mini"}},"features":{"enableResearch":false,"enableTelemetry":true},"targets":{"dhs_submission_rate":100,"eod_submission_rate":95,"follow_ups_per_day":5,"calls_per_day":8,"meetings_per_week":3,"upwork_proposals_per_week":10,"goals_on_track_percentage":80}}'::jsonb,
  true,
  true,
  '{"type":"scheduled","frequency":"weekly","day_of_week":"monday","time":"09:00","timezone":"America/New_York","enabled":true,"email_recipients":[]}'::jsonb,
  'manager',
  '["Automated weekly performance tracking","Comprehensive cross-module analysis","Early identification of at-risk reps","Data-driven coaching recommendations","Ready-to-use WIG agendas","80% reduction in manual reporting time"]'::jsonb,
  '["Weekly team performance review","Manager preparation for 1-on-1 meetings","Quarterly goal progress tracking","BD pipeline health monitoring","Team meeting agenda generation","Performance trend analysis"]'::jsonb,
  (SELECT id FROM profiles WHERE email ILIKE '%admin%' LIMIT 1)
)
ON CONFLICT (slug) DO NOTHING;